name: Generate Snake Graph

on:
  schedule:
    - cron: "0 */12 * * *"   # 12시간마다 자동 실행
  workflow_dispatch:         # 수동 실행 가능
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: junhyeokk97
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Upload artifact (v4 최신 버전)
        uses: actions/upload-artifact@v4
        with:
          name: snake-svg
          path: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
